-- Query A1
-- This is an incorrect way to define the aritmetic operations in a sql sentence
SELECT * FROM EMPLOYEES WHERE SALARY > AVG(SALARY);

-- Query A2

SELECT EMP_ID, F_NAME, L_NAME, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- Query A3
-- This is an incorrect way to define the aritmetic operations in a sql sentence
SELECT EMP_ID, F_NAME, L_NAME, SALARY, AVG(SALARY) FROM EMPLOYEES;

-- Query A4

SELECT EMP_ID, F_NAME, L_NAME, SALARY, (SELECT AVG(SALARY) FROM EMPLOYEES) AS AVG_SALARY FROM EMPLOYEES;

-- Query A5

SELECT * FROM (SELECT EMP_ID, F_NAME, L_NAME FROM EMPLOYEES) AS EMP;

-- Query B1

SELECT * FROM EMPLOYEES WHERE DEP_ID IN (SELECT DEPT_ID_DEP FROM DEPARTMENTS);

-- Query B2

SELECT EMP_ID, F_NAME, L_NAME FROM EMPLOYEES WHERE DEP_ID IN (SELECT DEPT_ID_DEP FROM DEPARTMENTS WHERE LOC_ID IN 'L0002');

-- Query B3

SELECT DEPT_ID_DEP, DEP_NAME FROM DEPARTMENTS WHERE DEPT_ID_DEP IN (SELECT DEP_ID FROM EMPLOYEES WHERE SALARY > 70000);

-- Query B4

SELECT * FROM EMPLOYEES, DEPARTMENTS;

-- Query B5

SELECT * FROM EMPLOYEES, DEPARTMENTS WHERE EMPLOYEES.DEP_ID = DEPARTMENTS.DEPT_ID_DEP;

-- Query B6

SELECT * FROM EMPLOYEES E, DEPARTMENTS D WHERE E.DEP_ID = D.DEPT_ID_DEP;

-- Query B7

SELECT EMP_ID, DEP_NAME FROM EMPLOYEES E, DEPARTMENTS D WHERE E.DEP_ID = D.DEPT_ID_DEP;

-- Query B8

SELECT E.EMP_ID, D.DEP_NAME FROM EMPLOYEES E, DEPARTMENTS D WHERE E.DEP_ID = D.DEPT_ID_DEP;


