-- Query A1

SELECT SUM(COST) FROM PETRESCUE;

-- Query A2

SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;

-- Query A3

SELECT MAX(QUANTITY) FROM PETRESCUE;

-- Query A4

SELECT AVG(COST) FROM PETRESCUE;

-- Query A5

SELECT AVG(COST / QUANTITY) FROM PETRESCUE WHERE LOWER(ANIMAL) IN ('dog');

-- Query B1

SELECT ID,  ANIMAL, ROUND(COST,0) FROM PETRESCUE;

-- Query B2

SELECT LENGTH(ANIMAL) FROM PETRESCUE;

-- Query B3

SELECT UPPER(ANIMAL) FROM PETRESCUE;

-- Query B4

SELECT DISTINCT(UPPER(ANIMAL)) FROM PETRESCUE;

-- Query B5

SELECT * FROM PETRESCUE WHERE LOWER(ANIMAL) IN ('cat');

-- Query C1

SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE LOWER(ANIMAL) IN ('cat');

-- Query C2

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE) = '05';

-- Query C3

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE) = '14';

-- Query C4

SELECT ID, ANIMAL, QUANTITY, COST, RESCUEDATE + 3 DAYS FROM PETRESCUE;

-- Query C5

SELECT ID, ANIMAL, CURRENT_DATE-RESCUEDATE FROM PETRESCUE;
